# Generated by Django 5.1.1 on 2024-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=10)),
                ('packet_type', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=20)),
                ('source_port', models.CharField(max_length=10)),
                ('destination_port', models.CharField(max_length=10)),
                ('sequence', models.CharField(blank=True, max_length=20, null=True)),
                ('ack', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
