# Generated by Django 4.2.16 on 2024-09-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_anomaly_networktraffic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktraffic',
            name='data',
        ),
    ]
